version: "3"
services:
   kafka1:
     image: 'bitnami/kafka:3.3'
     ports:
       - '9092:19092'
     environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:19092
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
       - KAFKA_BROKER_ID=1
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_KRAFT_CLUSTER_ID=U1UQCYWQQWCNTGEQY41nHw

   kafka2:
     image: 'bitnami/kafka:3.3'
     ports:
       - '9093:19093'
     environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093,CONTROLLER://:19093
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9093
       - KAFKA_BROKER_ID=2
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_KRAFT_CLUSTER_ID=U1UQCYWQQWCNTGEQY41nHw

   kafka3:
     image: 'bitnami/kafka:3.3'
     ports:
       - '9094:19094'
     environment:
       - KAFKA_ENABLE_KRAFT=yes
       - KAFKA_CFG_PROCESS_ROLES=broker,controller
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:19094
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9094
       - KAFKA_BROKER_ID=3
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_KRAFT_CLUSTER_ID=U1UQCYWQQWCNTGEQY41nHw
       
       
